# Generated by Django 4.2.1 on 2023-08-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='liter',
            field=models.CharField(blank=True, choices=[('0.5 L', '0.5 L'), ('1 L', '1 L'), ('1.5 L', '1.5 L'), ('2 L', '2 L')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='porsiya',
            field=models.CharField(blank=True, choices=[('05_HISSA', '05_HISSA'), ('ODATIY', 'ODATIY')], max_length=10, null=True),
        ),
    ]
