# Generated by Django 4.2.1 on 2023-08-25 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_drink', models.CharField(choices=[('0.5 L', '0.5 L'), ('1 L', '1 L'), ('1.5 L', '1.5 L'), ('2 L', '2 L')], default='1 L', max_length=10)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='mainapp.meal')),
            ],
        ),
    ]
